camunda.bpm.metrics.enabled=false
camunda.bpm.admin-user.id=demo
camunda.bpm.admin-user.password=demo
camunda.bpm.admin-user.first-name=demo
server.port=8082

app.envs-dir=src/main/resources/envs

spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false

# Participant scenario configuration (university, farm, emergency, rental)
# app.scenario=university